language: generic

os: linux

sudo: false

env:
  global:
    - CABALVER=1.24
  matrix:
    - GHCVER=7.10.3
    - GHCVER=8.0.2
    - GHCVER=8.2.2
    - GHCVER=8.4.1

addons:
  apt:
    packages:
      - cabal-install-$CABALVER
      - ghc-$GHCVER
    sources: hvr-ghc

cache:
  directories:
    - ~/.ghc
    - ~/.cabal

matrix:
  include:
    # MacOS requires specific matrix entries
    - env: GHCVER=8.0.2
      os: osx
    - env: GHCVER=8.2.2
      os: osx

  allow_failures:
    - env: GHCVER=8.4.1

before_install:
  # MacOS setups
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  # Install specific GHC version
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$GHCVER" == "8.0.2" ]]; then brew install ghc@8.0 cabal-install; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$GHCVER" == "8.2.2" ]]; then brew install ghc     cabal-install; fi

  # Linux setups
  # Export PATH to specifically installed Cabal & GHC versions
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH; fi

install:
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - travis_retry cabal update
  - cabal install --enable-benchmarks --enable-tests --only-dependencies
  - cabal install hpc-coveralls

script:
  - cabal configure --enable-coverage --enable-benchmarks --enable-tests -v2
  - cabal sdist
  - cabal build
  - cabal test --show-details=always
  - cabal check
  - cabal haddock

after_script:
  - export PATH=~/.cabal/bin:$PATH
  - hpc-coveralls --coverage-mode=StrictlyFullLines
                  --exclude-dir=bench
                  --exclude-dir=tests
                  test-suite

notifications:
  email: false
