cache:
  directories:
    - ~/.ghc
    - ~/.cabal

matrix:
  include:
    # MacOS builds
    - compiler: "ghc-7.10.3"
      env: CABALVER=1.24 GHCVER=7.10.3
    #  addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.3],sources: [hvr-ghc]}}
      os: osx
      language: generic
    - compiler: "ghc-8.0.2"
      env: CABALVER=1.24 GHCVER=8.0.2
    #  addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}
      os: osx
      language: generic
    - compiler: "ghc-8.2.2"
      env: CABALVER=1.24 GHCVER=8.2.2
    #  addons: {apt: {packages: [cabal-install-1.24,ghc-8.2.2], sources: [hvr-ghc]}}
      os: osx
      language: generic
    - compiler: "ghc-8.4.1"
      env: CABALVER=1.24 GHCVER=8.4.1
    #  addons: {apt: {packages: [cabal-install-1.24,ghc-8.4.1], sources: [hvr-ghc]}}
      os: osx
      language: generic

    # Linux builds
    - compiler: "ghc-7.10.3"
      env: CABALVER=1.24 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.3],sources: [hvr-ghc]}}
      os: linux
      language: haskell
      sudo: false
    - compiler: "ghc-8.0.2"
      env: CABALVER=1.24 GHCVER=8.0.2
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}
      os: linux
      language: haskell
      sudo: false
    - compiler: "ghc-8.2.2"
      env: CABALVER=1.24 GHCVER=8.2.2
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.2.2], sources: [hvr-ghc]}}
      os: linux
      language: haskell
      sudo: false
    - compiler: "ghc-8.4.1"
      env: CABALVER=1.24 GHCVER=8.4.1
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.4.1], sources: [hvr-ghc]}}
      os: linux
      language: haskell
      sudo: false

  allow_failures:
    - compiler: "ghc-8.4.1"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ghc-$GHCVER cabal-install-$CABALVER; fi
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - travis_retry cabal update
  - cabal install --enable-benchmarks --enable-tests --only-dependencies
  - cabal install hpc-coveralls

script:
  - cabal configure --enable-coverage --enable-benchmarks --enable-tests -v2
  - cabal sdist
  - cabal build
  - cabal test --show-details=always
  - cabal check
  - cabal haddock

after_script:
  - export PATH=~/.cabal/bin:$PATH
  - hpc-coveralls --coverage-mode=StrictlyFullLines
                  --exclude-dir=bench
                  --exclude-dir=tests
                  test-suite

notifications:
  email: false
